-- migrations/019_a4_endurecimiento.sql
-- #29 endurecimiento_preguntas
--
-- NO-OP intencional.
--
-- La versión original de esta migración borraba los 2 ítems A4 viejos de it-v2
-- (DELETE ... by label) e insertaba 5 nuevos. Era:
--   1. Destructiva: borraba audit_response (y, por la FK RESTRICT de
--      reunion_proposal.item_id, ni siquiera podía completarse cuando ya existía
--      una propuesta de reunión IA apuntando a un ítem viejo → 23503, boot en loop).
--   2. Redundante: el seeder de plantillas (src/lib/server/db/seed/templates.ts),
--      que corre en cada arranque DESPUÉS de las migraciones, ya aplica el cambio
--      de forma NO destructiva: hace UPDATE de template_item por (section_id,
--      sort_order), reusando la fila viva (mismo UUID) e insertando solo los
--      faltantes. Las respuestas y propuestas IA existentes quedan intactas, ahora
--      vinculadas a las preguntas nuevas en las mismas posiciones 0 y 1.
--
-- El cambio real de A4 vive 100% en seed/templates/it-v2.json (5 ítems, sort_order
-- 0..4). El test tests/templates/a4-endurecimiento.test.ts valida ese JSON.
--
-- Esta migración se deja como no-op (en vez de borrarse) para no alterar el
-- historial de schema_migration en entornos donde la versión anterior ya corrió.

SELECT 1;
