// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelarEscaneo() {
  return window['go']['main']['App']['CancelarEscaneo']();
}

export function ChequearActualizacion() {
  return window['go']['main']['App']['ChequearActualizacion']();
}

export function DescartarReanudacion(arg1) {
  return window['go']['main']['App']['DescartarReanudacion'](arg1);
}

export function EscaneosReanudables() {
  return window['go']['main']['App']['EscaneosReanudables']();
}

export function EstadoDocker() {
  return window['go']['main']['App']['EstadoDocker']();
}

export function ExportarLogs() {
  return window['go']['main']['App']['ExportarLogs']();
}

export function IniciarEscaneo(arg1, arg2) {
  return window['go']['main']['App']['IniciarEscaneo'](arg1, arg2);
}

export function InstalarDocker() {
  return window['go']['main']['App']['InstalarDocker']();
}

export function Progreso() {
  return window['go']['main']['App']['Progreso']();
}

export function ReintentarCola() {
  return window['go']['main']['App']['ReintentarCola']();
}

export function ValidarToken(arg1) {
  return window['go']['main']['App']['ValidarToken'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
