// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {scan} from '../models';

export function CancelarEscaneo():Promise<void>;

export function ChequearActualizacion():Promise<app.AvisoVersionDTO>;

export function DescartarReanudacion(arg1:string):Promise<void>;

export function EscaneosReanudables():Promise<Array<string>>;

export function EstadoDocker():Promise<void>;

export function ExportarLogs():Promise<string>;

export function IniciarEscaneo(arg1:Array<app.CredencialDTO>,arg2:string):Promise<void>;

export function InstalarDocker():Promise<void>;

export function Progreso():Promise<scan.ScanProgreso>;

export function ReintentarCola():Promise<void>;

export function ValidarToken(arg1:string):Promise<app.EscaneoInfoDTO>;

export function Version():Promise<string>;
